### ISSUE TITLE
Explore some charting libraries 

### ISSUE THREAD

**Issue by dyl10s** [dyl10s/TimeTracker#66]

**Comment by jwaltt55** [comment]
There are a few different charting libraries to pick from:

- ngx-charts is a really popular one that's used with angular a lot
- Chart.js is a Javascript charting library that has a lot of wrappers available for it (ngx-chartjs, react-chartjs, etc.)
- d3 is a data visualization library that could also be pretty useful

They kind of do the same thing, so it'd really just be a matter of picking one that's easy/intuitive to use, or one that some members of the team have had experience with before.

**Comment by dyl10s** [comment]
Looks good me! We can talk about this in our meeting tonight!
